// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx0Kk5NsuG88R8i5SPYgk7bZ93N9XRQR4',
    appId: '1:495115537471:web:876d5813fd0d17b1c83c8a',
    messagingSenderId: '495115537471',
    projectId: 'ayahcare-app-7866',
    authDomain: 'ayahcare-app-7866.firebaseapp.com',
    storageBucket: 'ayahcare-app-7866.firebasestorage.app',
    measurementId: 'G-2GXCLYB8ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADsdbGEjznS6rfAqXoqtdyw2ZhIHAkGtw',
    appId: '1:495115537471:android:10a167b9f86c6777c83c8a',
    messagingSenderId: '495115537471',
    projectId: 'ayahcare-app-7866',
    storageBucket: 'ayahcare-app-7866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL2tJYs5ASOTo6UiKftH5t-3pp4P0dBL8',
    appId: '1:495115537471:ios:bff54f9bc04b1445c83c8a',
    messagingSenderId: '495115537471',
    projectId: 'ayahcare-app-7866',
    storageBucket: 'ayahcare-app-7866.firebasestorage.app',
    iosBundleId: 'com.example.ayahcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL2tJYs5ASOTo6UiKftH5t-3pp4P0dBL8',
    appId: '1:495115537471:ios:bff54f9bc04b1445c83c8a',
    messagingSenderId: '495115537471',
    projectId: 'ayahcare-app-7866',
    storageBucket: 'ayahcare-app-7866.firebasestorage.app',
    iosBundleId: 'com.example.ayahcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx0Kk5NsuG88R8i5SPYgk7bZ93N9XRQR4',
    appId: '1:495115537471:web:1c45264b424b8094c83c8a',
    messagingSenderId: '495115537471',
    projectId: 'ayahcare-app-7866',
    authDomain: 'ayahcare-app-7866.firebaseapp.com',
    storageBucket: 'ayahcare-app-7866.firebasestorage.app',
    measurementId: 'G-QMMYBJWJ0K',
  );
}
